spring.application.name=project-spring-boot
server.port=8080
server.servlet.context-path=/api/v1
app.name=Student Management System
logging.level.com.student.management=DEBUG
spring.security.user.name=hahihi
spring.security.user.password=abc@123
